### PR TITLE
update to add Geexolotls

### PR DESCRIPTION
**Pull request by bcts1100**
added Geexolotls pools

### CODE REVIEW

**Comment by jpbogle** [comment]
not sure what the extra files are for, can you limit the change to `mapping.ts`?

**Comment by bcts1100** [comment]
The only other files are the logo, and a background image. There was some
testing on our server but no changes should have been made

**Comment by jpbogle** [comment]
the PR has 11 files changes

**Comment by bcts1100** [comment]
ok ill close this one and do a fresh one with just those files

**Pull request closed without merging**
