### PR TITLE
Fix/UI issues

### PR DESCRIPTION
**Pull request by metalgear-dev**
Fixed some notification messages

### CODE REVIEW

**Comment by jpbogle** [comment]
thanks @metalgear-dev !

**Comment by jpbogle** [comment]
looks like there may be some merge conflict, can you rebase the PR?

**Comment by metalgear-dev** [comment]
> looks like there may be some merge conflict, can you rebase the PR?

I don't think so.
Here it says "This branch has no conflicts with the base branch".

**Comment by metalgear-dev** [comment]
I think there are no conflicts. Please check it.

**Comment by gchatz22** [comment]
thanks @metalgear-dev, merging

**Pull request merged**
