### PR TITLE
cheesecomputer-draftjourney

### PR DESCRIPTION
**Pull request by arrowxgoutam**

### CODE REVIEW

**Comment by gchatz22** [comment]
you have two subdomains for the same pool, you should change one of the pools

**Comment by arrowxgoutam** [comment]
This is my pool address H7CFeUboerg7w3RaU8apsPJwkU4zW1fPXenQygiHPFn3  and i wand to add this domain cheesecomputer.draftjourney.io  so how can i do it ..? please advice me or help me..

**Comment by gchatz22** [comment]
https://github.com/cardinal-labs/cardinal-staking-ui#custom-hostname

**Comment by arrowxgoutam** [comment]
i follow this instruction , i add pool address and domain . then i create a pull request , but PR not complete . and i also change DNS  //cname.vercel-dns.com// . but showing cardinal home page.

**Comment by arrowxgoutam** [comment]
and after create pull request showing Vercel — Authorization required to deploy. //

**Comment by gchatz22** [comment]
image
what im saying is this thought. you have two domain under the same stake pool

**Comment by arrowxgoutam** [comment]
i remove one domain and try PR . but same issue.

**Comment by arrowxgoutam** [comment]
or you can add this from your site..

 {
    stakePoolAddress: 'H7CFeUboerg7w3RaU8apsPJwkU4zW1fPXenQygiHPFn3',
    hostname: 'cheesecomputer.draftjourney.io',
  },

**Comment by arrowxgoutam** [comment]
Hello mate,
Please approve this PR..

**Pull request merged**
